### ISSUE TITLE
Archive Name/Prefix field is not sanitized: inappropriate characters such as "/" needs to be replaced before saving

### ISSUE THREAD

**Issue by Wikinaut** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#10]
I use this version of the extension

![grafik](https://user-images.githubusercontent.com/1151915/78783280-a7cbc180-79a3-11ea-8f34-9e65c71603a3.png)

#### Problem
I gave the Name/Prefix as shown, but this leads to an error when borgbackup tries to backup. 

#### Solution
The input must be sanitized! Please change forbidden charactes like "/" to "_" or "-" and/or warn the user before saving such invalid Name/Prefixes.

![grafik](https://user-images.githubusercontent.com/1151915/78783386-d77ac980-79a3-11ea-8b9f-d2f47f250166.png)

**Comment by ryecoaaron** [comment]
That is a label not the format you should put name in.  The '/' is just a separator to shorten the label since it means "name of prefix".  I guess I can try to limit what characters can be typed in the field but this is very low on my priority list since you can just type letters and numbers to avoid the "problem".

**Comment by Wikinaut** [comment]
@ryecoaaron Respectfully stated, this is not the answer I had expected. You give an answer to a problem you don't have - because you are developer. I however explain a problem which can arise to everyone not having your expert knowledge.

**Comment by ryecoaaron** [comment]
You didn't respond to my answer you didn't like for over three weeks.  So, I assumed it was good enough.

You don't have to be an expert.  The field is just looking for a name.  The label is meant to be short not the format you enter the name in.  If the note doesn't explain that well enough then maybe it should be changed.  But sanitizing the input is not correct solution (although I understand there are illegal characters that I never tried).  I can try to eliminate illegal characters but you should instead suggest changes to the note so that people understand what to enter in the field.

**Comment by ryecoaaron** [comment]
Illegal characters can no longer be entered - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/commit/0c3e05f6d187d1ab8dc5f2f9e9ffe3b2b2fe25b6

**Comment by Wikinaut** [comment]
Well done, that looks fine to me. Thanks!
