### ISSUE TITLE
Local repo in a shard folder subfolder?

### ISSUE THREAD

**Issue by mauromol** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#23]
If I understand this plugin interface well, you can create a local borg repository only directly into a OMV Shared Folder.
It would be nice if I could select a Shard Folder subfolder as the repo root.
I.e.: I have a "Backup" Shared Folder, then I can set "Backup/borg/my-repo" as the actual repo.
Right now, unless I'm missing something, I have to declare a "my-repo" Shared Folder rooted at the above subfolder to obtain this result, correct me if I'm wrong.

**Comment by ryecoaaron** [comment]
That is correct.  That is why you can create sharedfolders from subfolders.  Adding the ability to choose subfolder in the plugin would be duplicating the ability to do that in the sharedfolder creation in my opinion.

**Comment by mauromol** [comment]
I understand your point of view, however IMHO a "shared folder" should be some relevant folder for which one or more (kind of) services should be activated. In this sense, having a "backup" shared folder aimed at hosting backups makes sense, just like having a "multimedia" folder for multimedia files, a "home" folder to have user homes, and so on. Having to create a "shared folder" for each of the borg repositories you want to host is a bit of a forcing and makes OMV configuration more complex, IMHO.

But perhaps it's just a different point of view.

**Comment by ryecoaaron** [comment]
If that line of thinking is used, then services like nfs and samba would also need to offer a way to specify a path since you would just be using a nfs or samba shared folder.  I really don't have a strong opinion either way but I prefer to keep the plugin like the rest of OMV.

One benefit of creating more shared folders is that they can be used with more than one plugin without having to define the folder structure again.  And if you need to change it, you only have to change it in one place.
