### ISSUE TITLE
Set scheduled time for daily/weekly/monthly backups

### ISSUE THREAD

**Issue by maurice1** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#38]
Is it possible to set the scheduled time for daily backup archives? I've several archives where the "retain hourly" value is 0. Borgbackup seems to be configured to run at 2:30 am. However, the system is offline at that time (due to the AutoShutdown plugin). I'd like borgbackups to run when the system is awake, preferably sequentially starting at a given time.
Is that possible using the UI? (this might be a feature request ;-)

**Comment by ryecoaaron** [comment]
You can set the environment variable - OMV_BORGBACKUP_STARTING_HOUR - that determines the start time for the cron job.  https://docs.openmediavault.org/en/5.x/various/advset.html (this works on 6.x too).

**Comment by maurice1** [comment]
Thanks @ryecoaaron! This worked just fine :-) Could this be a configuration option on the archive settings page? Or cronjobs that are available through the "scheduled tasks" page. When adding an archive configuration, a cronjob could be created in the scheduled tasks instead. That way users could change the schedule or just leave it on defaults.

**Comment by ryecoaaron** [comment]
It cant be in the archives page since there is only one cronjob that run all jobs since it really is meant to run hourly.  scheduled tasks would require keeping two database entries in sync. Most people wouldn’t like creating a scheduled task for hourly, daily, weekly, monthly, and yearly for every archive. The little bit of flexibility would be a lot more to setup and maintain.

**Comment by maurice1** [comment]
I understand, thank you :)
