### ISSUE TITLE
Failed to execute  'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; BORG_PASSPHRASE='dummy' /usr/bin/borg init --encryption=keyfile '/srv/dev-disk-by-label-myraid/nas'' with exit code '2':

### ISSUE THREAD

**Issue by Wikinaut** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#4]
I wanted to setup OMV with the borgbackup plugin, but failed at the very first step (when adding a Paketquelle). Pls. assist.

And, by the way, is there any documentation available?

```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; BORG_PASSPHRASE='dummy' /usr/bin/borg init --encryption=keyfile '/srv/dev-disk-by-label-myraid/nas'' with exit code '2':

Fehler #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; BORG_PASSPHRASE='dummy' /usr/bin/borg init --encryption=keyfile '/srv/dev-disk-by-label-myraid/nas'' with exit code '2':  in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/borgbackup.inc(152): OMV\System\Process->execute(Array)
#1 [internal function]: OMVRpcServiceBorgBackup->setRepo(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setRepo', Array, Array)
#4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('BorgBackup', 'setRepo', Array, Array, 1)
#5 {main}
```

**Comment by ryecoaaron** [comment]
What is a Paketquelle?

The only documentation available is the borgbackup documentation - https://borgbackup.readthedocs.io/en/stable/.  I tried to leave terms in the plugin the same.  So, the process to do things should be the same as in their docs.

**Comment by Wikinaut** [comment]
@ryecoaaron here's a screenshot of the panel of this plugin:
![grafik](https://user-images.githubusercontent.com/1151915/62133089-84158f00-b2de-11e9-8a8c-51e5099c9d2b.png)

**Comment by ryecoaaron** [comment]
The plugin is very good for compressed, deduplicated backups that can optionally be encrypted.  Is that your need?

**Comment by Wikinaut** [comment]
I am using Borgbackup,but currently not with the plugin. Please explain, what it does.

**Comment by ryecoaaron** [comment]
The plugin executes borgbackup commands like creating repos, archives, and such.  If you are familiar with borgbackup, does the plugin not make sense with how you normally use it?

**Comment by Wikinaut** [comment]
I may do so, but why does it (the plugin) bring the above mentioned error?

**Comment by ryecoaaron** [comment]
Not sure.  Might have been a change to borgbackup.  I will have to test.

**Comment by ryecoaaron** [comment]
Is the selected sharedfolder empty?  borg won't use a folder with anything in it.

**Comment by Wikinaut** [comment]
@ryecoaaron Ah! No, the only selectable shared folder which was shown was the (only) shared folder which I already used for my (manually set up) borgbackup.
Now I added a new shared folder and could add this.

Closing this issue now, but I will file a new issue with a modified subject, because I think that such a problem (folder/backup repo already exists) should be covered and signalled properly.

**Comment by Arzamas** [comment]
I have a similar error in OMV5 when I try to mount a drive

`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run fstab 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working if not isinstance(exes, collections.Iterable): /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly *salt.utils.args.get_function_argspec(original_function) nanopim4: ---------- ID: create_filesystem_mountpoint_110da769-901d-4e0d-b38b-0abd88f7c8c2 Function: file.accumulated Result: True Comment: Accumulator create_filesystem_mountpoint_110da769-901d-4e0d-b38b-0abd88f7c8c2 for file /etc/fstab was charged by text Started: 21:52:26.337983 Duration: 1.697 ms Changes: ---------- ID: mount_filesystem_mountpoint_110da769-901d-4e0d-b38b-0abd88f7c8c2 Function: mount.mounted Name: /srv/dev-disk-by-label-Untitled Result: False Comment: mount: /srv/dev-disk-by-label-Untitled: unknown filesystem type 'exfat'. Started: 21:52:26.357959 Duration: 1075.033 ms Changes: ---------- ID: append_fstab_entries Function: file.blockreplace Name: /etc/fstab Result: True Comment: Changes were made Started: 21:52:27.434826 Duration: 11.381 ms Changes: ---------- diff: --- +++ @@ -1,2 +1,5 @@ UUID=3795425a-ea8c-4a26-8861-09da07c2eddc / ext4 defaults,noatime,nodiratime,commit=600,errors=remount-ro 0 1 tmpfs /tmp tmpfs defaults,nosuid 0 0 +# >>> [openmediavault] +/dev/disk/by-label/Untitled /srv/dev-disk-by-label-Untitled exfat defaults,nofail 0 2 +# <<< [openmediavault] Summary for nanopim4 ------------ Succeeded: 2 (changed=1) Failed: 1 ------------ Total states run: 3 Total run time: 1.088 s    `



`    Ошибка #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run fstab 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(exes, collections.Iterable):
/usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)
nanopim4:
----------
          ID: create_filesystem_mountpoint_110da769-901d-4e0d-b38b-0abd88f7c8c2
    Function: file.accumulated
      Result: True
     Comment: Accumulator create_filesystem_mountpoint_110da769-901d-4e0d-b38b-0abd88f7c8c2 for file /etc/fstab was charged by text
     Started: 21:52:26.337983
    Duration: 1.697 ms
     Changes:
----------
          ID: mount_filesystem_mountpoint_110da769-901d-4e0d-b38b-0abd88f7c8c2
    Function: mount.mounted
        Name: /srv/dev-disk-by-label-Untitled
      Result: False
     Comment: mount: /srv/dev-disk-by-label-Untitled: unknown filesystem type 'exfat'.
     Started: 21:52:26.357959
    Duration: 1075.033 ms
     Changes:
----------
          ID: append_fstab_entries
    Function: file.blockreplace
        Name: /etc/fstab
      Result: True
     Comment: Changes were made
     Started: 21:52:27.434826
    Duration: 11.381 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,2 +1,5 @@
                   UUID=3795425a-ea8c-4a26-8861-09da07c2eddc / ext4 defaults,noatime,nodiratime,commit=600,errors=remount-ro 0 1
                   tmpfs /tmp tmpfs defaults,nosuid 0 0
                  +# >>> [openmediavault]
                  +/dev/disk/by-label/Untitled        /srv/dev-disk-by-label-Untitled    exfat    defaults,nofail    0 2
                  +# <<< [openmediavault]

Summary for nanopim4
------------
Succeeded: 2 (changed=1)
Failed:    1
------------
Total states run:     3
Total run time:   1.088 s in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(907): OMV\Rpc\Rpc::call('Config', 'applyChanges', Array, Array)
#6 [internal function]: Engined\Rpc\OMVRpcServiceFileSystemMgmt->mount(Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#8 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('mount', Array, Array)
#9 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('FileSystemMgmt', 'mount', Array, Array, 1)
#10 {main}
`

**Comment by ryecoaaron** [comment]
This isn’t the fault of the borg plugin. Your nanopi’s kernel doesn’t have exfat module. So it is failing to mount exfat filesystem.

**Comment by Arzamas** [comment]
> This isn’t the fault of the borg plugin. Your nanopi’s kernel doesn’t have exfat module. So it is failing to mount exfat filesystem.

Yes, I know that this is not this module, I just got here on Google )) 

but I'm trying to mount the disks on ext4
not exfat

Yes, the exfat disk is installed in the hub, but I did not mount it.

**Comment by Arzamas** [comment]
> This isn’t the fault of the borg plugin. Your nanopi’s kernel doesn’t have exfat module. So it is failing to mount exfat filesystem.

but you were right! I took out the exfat disk from the hub and it worked! Thanks for the idea! Have a good time!
